name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: |
         cd ..
         git clone https://github.com/Microsoft/DirectXTK12.git
         cd DirectXTK12
         git clone https://github.com/walbourn/directxtk12test.git Tests
         git clone https://github.com/Microsoft/DirectXTK12.wiki.git wikicmake --preset=x64-Debug
         cmake build out\build\x64-Debug
         ctest --preset=x64-Debug
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - uses: actions/upload-artifact@v4
      with:
          name: test.zip
          path: out
